### PR TITLE
Fix #97 & #98

### LINKED ISSUE #97: Python simple block body
**Language**
Python

**Polygolf source**

```
for $i 0 10 {
    $a <- $i;
    println $a;
};
```

**Current output**

```
for i in range(10):
 a=i
 print(a)
```

**Expected output**

```
for i in range(10):a=i;print(a)
```

**Comment**
Code is valid but unnecesarily longer.

### LINKED ISSUE #98: Nim simple block body
**Language**
Nim

**Polygolf source**

```
for $i 0 10 {
    println $i;
    println $i;
};
```

**Current output**

```
for i in..9:
 i.echo
 i.echo
```

**Expected output**

```
for i in..9:i.echo;i.echo
```

**Comment**
Code is valid but unnecesarily longer.

### PR DESCRIPTION
**Pull request by MeWhenI**
Is there a reason I'm not aware of for node to be considered one of its own children? Otherwise, this fixes the issue.

Edit so Github knows which issues this closes:
Fixes #97 
Fixes #98

### CODE REVIEW

**Comment by MeWhenI** [comment]
I suppose to link to the issue I need to actually write out
Fixes #97 
Fixes #98

**Comment by MeWhenI** [comment]
Converting to draft, I see that clashes with other tests

**Comment by MeWhenI** [comment]
This seems janky. I assert that unless there's a compelling reason why not, any node whos child can be a Block (While, For, If), should have to have a Block as its child, and only Blocks themselves can have non-Block children. So instead of
```
{
 kind="While"
 body={
  kind="If"
 }
}
```
we would have
```
{
 kind="While"
 body={
  kind="Block"
  body=[
    {
     kind="If"
   },
  ]
 }
}
```
. It seems unintuitive that in any case anything other than a Block should be getting passed to `emitBlock`.

**Comment by MichalMarsalek** [comment]
> This seems janky. I assert that unless there's a compelling reason why not, any node whos child can be a Block (While, For, If), should have to have a Block as its child, and only Blocks themselves can have non-Block children. So instead of
> 
> ```
> {
>  kind="While"
>  body={
>   kind="If"
>  }
> }
> ```
> 
> we would have
> 
> ```
> {
>  kind="While"
>  body={
>   kind="Block"
>   body=[
>     {
>      kind="If"
>    },
>   ]
>  }
> }
> ```
> 
> . It seems unintuitive that in any case anything other than a Block should be getting passed to `emitBlock`.

It actually used to have exactly this, and decided to switch to bodies being Exprs.

**Comment by MichalMarsalek** [comment]
It would be nice if the top level separator was `\n` and not `;`.

**Comment by MeWhenI** [comment]
@MichalMarsalek emitBlock refactored to emitMultiExpr which I think more accurately reflects what it does. And yeah gotcha newlines do have a nice look to them.

**Pull request merged**
